version: "3.5"

services:
  workshops_de_ttt_prisma_db:
    image: "mariadb:latest"
    restart: 'always'
    container_name: workshops_de_ttt_prisma_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: prisma

  workshops_de_ttt_prisma_db_prod:
    image: "mariadb:latest"
    restart: 'always'
    container_name: workshops_de_ttt_prisma_db_prod
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: prisma
